### ISSUE TITLE
A few:

### ISSUE THREAD

**Issue by TheRoyalBlock** [Ultie0/MagicalCat#1]
On heroku, this crashes
```
2017-05-06T20:20:37.311894+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=royalcats.herokuapp.com request_id=9b7e90d3-4da9-4e7c-b1ca-eaa044271665 fwd="108.6.241.138" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by Ultie0** [comment]
Heroku thinks this is a webapp. Go to resources in your panel and you should see two things:

`web      npm start
  bot       node app.js `

at the right of each one there is a pencil, click it and change the slider so **web is turned off** and **bot is turned on**. It would look like this:
![img_3458](https://cloud.githubusercontent.com/assets/6726237/25777542/d54b8118-32e8-11e7-8ab0-80dd8ca93635.PNG)

**Comment by TheRoyalBlock** [comment]
ok thanks!

**Comment by TheRoyalBlock** [comment]
Now how do I add it to a discord server? Sorry if I'm such a noob at heroku.

**Comment by Ultie0** [comment]
Get your bot client ID.
`https://discordapp.com/oauth2/authorize?client_id=YOURIDHERE&scope=bot&permissions=305212430`
and visit the link, replacing YOURIDHERE with the bot client ID.

**Comment by TheRoyalBlock** [comment]
alrighty, thanks!
